active:
    path: /active
    defaults: { _controller: AppBundle:Page:active }
    methods: [POST]

index:
    path: /
    defaults: { _controller: AppBundle:Page:index }
    methods: [GET]

index_edit:
    path: /index-edit
    defaults: { _controller: AppBundle:Page:editIndex }
    methods: [GET, POST]

errorr:
    path: /errorr
    defaults: { _controller: AppBundle:Page:errorr }

login:
    path: /login
    defaults: { _controller: AppBundle:Users:login }
    methods: [GET, POST]

logout:
    path: /logout
    defaults: { _controller: AppBundle:Users:logout }
    methods: [GET]

register:
    path: /register
    defaults: { _controller: AppBundle:Users:register }
    methods: [GET, POST]

recover:
    path: /recover/{token}
    defaults: { _controller: AppBundle:Users:recover, token: null }
    methods: [GET, POST]

recover_password:
    path: /recover-password
    defaults: { _controller: AppBundle:Users:recoverPassword }
    methods: [GET, POST]

news:
    path: /news
    defaults: { _controller: AppBundle:News:list }
    methods: [GET]

news_view:
    path: /news/{id}
    defaults: { _controller: AppBundle:News:view }
    requirements:
        id: \d+
    methods: [GET]

news_new:
    path: /news-new
    defaults: { _controller: AppBundle:News:new }
    methods: [GET, POST]

news_edit:
    path: /news-edit/{id}
    defaults: { _controller: AppBundle:News:edit }
    requirements:
        id: \d+
    methods: [GET, POST]

news_delete:
    path: /news-delete/{id}
    defaults: { _controller: AppBundle:News:delete }
    requirements:
        id: \d+
    methods: [GET]

documents:
    path: /documents
    defaults: { _controller: AppBundle:Documents:list }
    methods: [GET]

document_new:
    path: /document-new
    defaults: { _controller: AppBundle:Documents:new }
    methods: [GET, POST]

document_edit:
    path: /document-edit/{id}
    defaults: { _controller: AppBundle:Documents:edit }
    requirements:
        id: \d+
    methods: [GET, POST]

document_delete:
    path: /document-delete/{id}
    defaults: { _controller: AppBundle:Documents:delete }
    requirements:
        id: \d+
    methods: [GET]

tariffs:
    path: /tariffs
    defaults: { _controller: AppBundle:Tariffs:list }
    methods: [GET]

tariff_new:
    path: /tariff-new
    defaults: { _controller: AppBundle:Tariffs:new }
    methods: [GET, POST]

tariff_edit:
    path: /tariff-edit/{id}
    defaults: { _controller: AppBundle:Tariffs:edit }
    requirements:
        id: \d+
    methods: [GET, POST]

tariff_delete:
    path: /tariff-delete/{id}
    defaults: { _controller: AppBundle:Tariffs:delete }
    requirements:
        id: \d+
    methods: [GET]

map:
    path: /map
    defaults: { _controller: AppBundle:Map:view }
    methods: [GET]

map_edit:
    path: /map-edit
    defaults: { _controller: AppBundle:Map:edit }
    methods: [GET, POST]

contacts:
    path: /contacts
    defaults: { _controller: AppBundle:Contacts:view }
    methods: [GET]

contacts_edit:
    path: /contacts-edit
    defaults: { _controller: AppBundle:Contacts:edit }
    methods: [GET, POST]

write:
    path: /write
    defaults: { _controller: AppBundle:Write:send }
    methods: [GET, POST]

sections:
    path: /sections
    defaults: { _controller: AppBundle:Discussions:sections }
    methods: [GET]

section_new:
    path: /section-new
    defaults: { _controller: AppBundle:Discussions:newSection }
    methods: [GET, POST]

section_edit:
    path: /section-edit/{id}
    defaults: { _controller: AppBundle:Discussions:editSection }
    requirements:
        id: \d+
    methods: [GET, POST]

section_delete:
    path: /section-delete/{id}
    defaults: { _controller: AppBundle:Discussions:deleteSection }
    requirements:
        id: \d+
    methods: [GET]

subjects:
    path: /subjects/{section}
    defaults: { _controller: AppBundle:Discussions:subjects }
    requirements:
        section: \d+
    methods: [GET]

subject_new:
    path: /subject-new/{section}
    defaults: { _controller: AppBundle:Discussions:newSubject }
    requirements:
        section: \d+
    methods: [GET, POST]

subject_edit:
    path: /subject-edit/{id}
    defaults: { _controller: AppBundle:Discussions:editSubject }
    requirements:
        id: \d+
    methods: [GET, POST]

subject_delete:
    path: /subject-delete/{id}
    defaults: { _controller: AppBundle:Discussions:deleteSubject }
    requirements:
        id: \d+
    methods: [GET]

messages:
    path: /messages/{subject}
    defaults: { _controller: AppBundle:Discussions:messages }
    requirements:
        subject: \d+
    methods: [GET]

message_delete:
    path: /message-delete/{id}/{subject}
    defaults: { _controller: AppBundle:Discussions:deleteMessage }
    requirements:
        id: \d+
        subject: \d+
    methods: [GET]

assessment:
    path: /assessment/{message}/{user}/{type}
    defaults: { _controller: AppBundle:Feedbacks:assessment }
    requirements:
        message: \d+
        user: \d+
        type: \d+
    methods: [GET]

complaints:
    path: /complaints
    defaults: { _controller: AppBundle:Feedbacks:complaints }
    methods: [GET]

complaint_new:
    path: /complaint-new/{message}
    defaults: { _controller: AppBundle:Feedbacks:newComplaint }
    requirements:
        message: \d+
    methods: [GET, POST]

blocks:
    path: /blocks
    defaults: { _controller: AppBundle:Blocks:list }
    methods: [GET]

block_new:
    path: /block-new/{user}
    defaults: { _controller: AppBundle:Blocks:new }
    requirements:
        user: \d+
    methods: [GET, POST]

unblock:
    path: /unblock/{user}
    defaults: { _controller: AppBundle:Blocks:unblock }
    requirements:
        user: \d+
    methods: [GET]

profile:
    path: /profile
    defaults: { _controller: AppBundle:Users:profile }
    methods: [GET, POST]

profiles:
    path: /profiles
    defaults: { _controller: AppBundle:Users:profiles }
    methods: [GET]

measurements:
    path: /measurements/{user}
    defaults: { _controller: AppBundle:Measurements:list }
    requirements:
        user: \d+
    methods: [GET]

measurement_new:
    path: /measurement-new/{user}
    defaults: { _controller: AppBundle:Measurements:new }
    requirements:
        user: \d+
    methods: [GET, POST]

measurement_edit:
    path: /measurement-edit/{id}
    defaults: { _controller: AppBundle:Measurements:edit }
    requirements:
        id: \d+
    methods: [GET, POST]

measurement_delete:
    path: /measurement-delete/{id}
    defaults: { _controller: AppBundle:Measurements:delete }
    requirements:
        id: \d+
    methods: [GET]

payments:
    path: /payments/{user}
    defaults: { _controller: AppBundle:Payments:list }
    requirements:
        user: \d+
    methods: [GET]

payment_new:
    path: /payment-new/{user}
    defaults: { _controller: AppBundle:Payments:new }
    requirements:
        user: \d+
    methods: [GET, POST]

payment_edit:
    path: /payment-edit/{id}
    defaults: { _controller: AppBundle:Payments:edit }
    requirements:
        id: \d+
    methods: [GET, POST]

payment_delete:
    path: /payment-delete/{id}
    defaults: { _controller: AppBundle:Payments:delete }
    requirements:
        id: \d+
    methods: [GET]

calculate_user:
    path: /calculate-user/{user}
    defaults: { _controller: AppBundle:Measurements:calculateUser }
    requirements:
        user: \d+
    methods: [GET]

set_role:
    path: /set-role/{user}/{role}
    defaults: { _controller: AppBundle:Users:setRole }
    requirements:
        user: \d+
        role: \w+
    methods: [GET]

user_delete:
    path: /user-delete/{id}
    defaults: { _controller: AppBundle:Users:delete }
    requirements:
        id: \d+
    methods: [GET]

read:
    path: /read
    defaults: { _controller: AppBundle:Messages:read }

inbox:
    path: /inbox
    defaults: { _controller: AppBundle:Messages:inbox }
    methods: [GET]

outbox:
    path: /outbox
    defaults: { _controller: AppBundle:Messages:outbox }
    methods: [GET]

letter:
    path: /letter
    defaults: { _controller: AppBundle:Messages:letter }
    methods: [GET, POST]

calculate:
    path: /calculate
    defaults: { _controller: AppBundle:Measurements:calculate }
    methods: [GET]